Update Query_BackUp set [Code] = NULL where [Code] = ''
Update Query_BackUp set [ProductType] = NULL where [ProductType] = ''
Update Query_BackUp set [Product] = NULL where [Product] = ''
Update Query_BackUp set [MasterCode] = NULL where [MasterCode] = ''
Update Query_BackUp set [ItemNumber] = NULL where [ItemNumber] = ''
Update Query_BackUp set [ProductCode] = NULL where [ProductCode] = ''
Update Query_BackUp set [ProductName] = NULL where [ProductName] = ''
Update Query_BackUp set [SearchName] = NULL where [SearchName] = ''
Update Query_BackUp set [ConfigurationTechnology] = NULL where [ConfigurationTechnology] = ''
Update Query_BackUp set [Configuration] = NULL where [Configuration] = ''
Update Query_BackUp set [ProductDimensionGroup] = NULL where [ProductDimensionGroup] = ''
Update Query_BackUp set [StorageDimensionGroup] = NULL where [StorageDimensionGroup] = ''
Update Query_BackUp set [TrackingDimensionGroup] = NULL where [TrackingDimensionGroup] = ''
Update Query_BackUp set [ItemModelGroup] = NULL where [ItemModelGroup] = ''
Update Query_BackUp set [ReservationHierarchy] = NULL where [ReservationHierarchy] = ''
Update Query_BackUp set [DCRpartnumber] = NULL where [DCRpartnumber] = ''
Update Query_BackUp set [WebUsage] = NULL where [WebUsage] = ''
Update Query_BackUp set [BuyerGroup] = NULL where [BuyerGroup] = ''
Update Query_BackUp set [Vendor] = NULL where [Vendor] = ''
Update Query_BackUp set [ItemSalesTaxGroup] = NULL where [ItemSalesTaxGroup] = ''
Update Query_BackUp set [ApprovedVendorCheckMethod] = NULL where [ApprovedVendorCheckMethod] = ''
Update Query_BackUp set [DirectDelivery] = NULL where [DirectDelivery] = ''
Update Query_BackUp set [DirectDeliveryWarehouse] = NULL where [DirectDeliveryWarehouse] = ''
Update Query_BackUp set [ChargesGroup] = NULL where [ChargesGroup] = ''
Update Query_BackUp set [LineDiscountGroup] = NULL where [LineDiscountGroup] = ''
Update Query_BackUp set [Commodity] = NULL where [Commodity] = ''
Update Query_BackUp set [BatchNumberGroup] = NULL where [BatchNumberGroup] = ''
Update Query_BackUp set [MassVolumeSize] = NULL where [MassVolumeSize] = ''
Update Query_BackUp set [MassVolumeUOM] = NULL where [MassVolumeUOM] = ''
Update Query_BackUp set [ShelfLifePeriodinDays] = NULL where [ShelfLifePeriodinDays] = ''
Update Query_BackUp set [BestBeforePeriodinDays] = NULL where [BestBeforePeriodinDays] = ''
Update Query_BackUp set [RestrictedProduct] = NULL where [RestrictedProduct] = ''
Update Query_BackUp set [Phantom] = NULL where [Phantom] = ''
Update Query_BackUp set [ProductionType] = NULL where [ProductionType] = ''
Update Query_BackUp set [CoverageGroup] = NULL where [CoverageGroup] = ''
Update Query_BackUp set [Supply Strategy Code] = NULL where [Supply Strategy Code] = ''
Update Query_BackUp set [Supply Strategy Description] = NULL where [Supply Strategy Description] = ''
Update Query_BackUp set [ItemGroup] = NULL where [ItemGroup] = ''
Update Query_BackUp set [CostGroup] = NULL where [CostGroup] = ''
Update Query_BackUp set [UseCostPricebyVariant] = NULL where [UseCostPricebyVariant] = ''
Update Query_BackUp set [AX_Value] = NULL where [AX_Value] = ''
Update Query_BackUp set [Revenue] = NULL where [Revenue] = ''
Update Query_BackUp set [BusinessUnit] = NULL where [BusinessUnit] = ''
Update Query_BackUp set [ProductClass] = NULL where [ProductClass] = ''
Update Query_BackUp set [PackSizeCategoryID] = NULL where [PackSizeCategoryID] = ''
Update Query_BackUp set [PhysicalDimensionGroupID] = NULL where [PhysicalDimensionGroupID] = ''
Update Query_BackUp set [Code1] = NULL where [Code1] = ''
Update Query_BackUp set [Code2] = NULL where [Code2] = ''
Update Query_BackUp set [Code3] = NULL where [Code3] = ''
Update Query_BackUp set [Code4] = NULL where [Code4] = ''
Update Query_BackUp set [UNNUMBER] = NULL where [UNNUMBER] = ''
Update Query_BackUp set [UNSPSCCODE] = NULL where [UNSPSCCODE] = ''
Update Query_BackUp set [IATAPackingGroup] = NULL where [IATAPackingGroup] = ''
Update Query_BackUp set [CategoryHierarchy] = NULL where [CategoryHierarchy] = ''
Update Query_BackUp set [DefaultOrderType] = NULL where [DefaultOrderType] = ''
Update Query_BackUp set [PurchaseSite] = NULL where [PurchaseSite] = ''
Update Query_BackUp set [InventorySite] = NULL where [InventorySite] = ''
Update Query_BackUp set [SalesSite] = NULL where [SalesSite] = ''
Update Query_BackUp set [OverrideSalesLeadTime] = NULL where [OverrideSalesLeadTime] = ''
Update Query_BackUp set [SalesLeadTime] = NULL where [SalesLeadTime] = ''
Update Query_BackUp set [OverrideDeliveryControl] = NULL where [OverrideDeliveryControl] = ''
Update Query_BackUp set [DeliveryDateControl] = NULL where [DeliveryDateControl] = ''
Update Query_BackUp set [ATPTimeFence] = NULL where [ATPTimeFence] = ''
Update Query_BackUp set [ATPBackwardDemandTimeFence] = NULL where [ATPBackwardDemandTimeFence] = ''
Update Query_BackUp set [ATPBackwardSupplyTimeFence] = NULL where [ATPBackwardSupplyTimeFence] = ''
Update Query_BackUp set [ATPDelayedDemandOffsetTime] = NULL where [ATPDelayedDemandOffsetTime] = ''
Update Query_BackUp set [ATPDelayedSupplyOffsetTime] = NULL where [ATPDelayedSupplyOffsetTime] = ''
Update Query_BackUp set [ATPIncl.PlannedOrders] = NULL where [ATPIncl.PlannedOrders] = ''
Update Query_BackUp set [Site] = NULL where [Site] = ''
Update Query_BackUp set [PurchaseWarehouse] = NULL where [PurchaseWarehouse] = ''
Update Query_BackUp set [InventoryWarehouse] = NULL where [InventoryWarehouse] = ''
Update Query_BackUp set [SalesWarehouse] = NULL where [SalesWarehouse] = ''
Update Query_BackUp set [PIPApprovedItemGroup] = NULL where [PIPApprovedItemGroup] = ''
Update Query_BackUp set [PIPCustomerCheckItem] = NULL where [PIPCustomerCheckItem] = ''
Update Query_BackUp set [PurchaseSTOPPED] = NULL where [PurchaseSTOPPED] = ''
Update Query_BackUp set [InventorySTOPPED] = NULL where [InventorySTOPPED] = ''
Update Query_BackUp set [SalesSTOPPED] = NULL where [SalesSTOPPED] = ''
Update Query_BackUp set [Unit] = NULL where [Unit] = ''
Update Query_BackUp set [SoldUnit] = NULL where [SoldUnit] = ''
Update Query_BackUp set [InventoryUnit] = NULL where [InventoryUnit] = ''
Update Query_BackUp set [BOM_Unit] = NULL where [BOM_Unit] = ''
Update Query_BackUp set [UnitUnitsequenceGroupID] = NULL where [UnitUnitsequenceGroupID] = ''

Update Query_BackUp
Set MassVolumeUOM = Null
where MassVolumeUOM = 'NULL'




Truncate Table Query_BackUp

INsert into Query_BackUp
select * from query 



Select top 1000 * from Query_BackUp