USE [MDSPOC]
GO
/****** Object:  StoredProcedure [dbo].[Add_properShipNames]    Script Date: 12/15/2020 11:55:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Christofer Rodriguez
-- Create date: 12/15/2020
-- Description:	Add proper shipping values 
-- =============================================
Create PROCEDURE [dbo].[Add_properShipNames] as 
BEGIN
Create Table #TempShipping
(
Code nvarchar(100),
[Name] nvarchar(1000),
IATA nvarchar(10),
UNNumber nvarchar(10)
)

Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637152076','Crotonic Acid, solid','8','UN2823')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637152826','Toxic Solid, Organis, N.O.S. (Thalidomide - Linker 5)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637171791','Alkylsulphonic acids, liquid solution','8','UN2586')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144576','Ethanol Solution','3','UN1170')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144577','Methanol','3(6.1)','UN1230')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144578','Methyl Acetate Solution','3','UN1231')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144579','Alkaloids salts, solid, n.o.s.','6.1','UN1544')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144580','Acetonitrile solution','3','UN1648')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144581','Nicotine preparation, solid, n.o.s.','6.1','UN1655')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144582','Nicotine Tartrate','6.1','UN1659')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144583','Strychnine salts','6.1','UN1692')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144584','Corrosive Solid, n.o.s.','8','UN1759')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144585','Corrosive liquid, n.o.s.','8','UN1760')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144586','Sodium Hydroxide Solution','8','UN1824')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144587','Alcohols, flammable, toxic, n.o.s.','3(6.1)','UN1986')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144589','Flammable liquid, toxic, n.o.s.','3(6.1)','UN1992')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144590','Mercury compound, liquid, n.o.s.','6.1','UN2024')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144591','Trichloroacetic Acid Solution','8','UN2564')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144592','Sulfuric Acid','8','UN2796')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144593','Toxic Solid, Organic, n.o.s.','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144594','Toxic liquid, Organic, n.o.s.','6.1','UN2810')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144596','Corrosive liquids, toxic, n.o.s.','8(6.1)','UN2922')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144597','Environmentally hazardous substance, solid, n.o.s.','9','UN3077')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144598','Environmentally Hazadous Substance, liquid, n.o.s.','9','UN3082')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144599','Corrosive solid,acidic, organic, n.o.s.','8','UN3261')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144600','Corrosive solid, basic, organic, n.o.s.','8','UN3263')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144601','Selenium compound, solid, n.o.s.','6.1','UN3283')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144602','Aviation regulated liquid n.o.s.','9','UN3334')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637144603','Toxins extracted from living sources, solid, n.o.s.','6.1','UN3462')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637145326','Hydrochloric acid','8','UN1789')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637146076','Flammable liquid, n.o.s','3','UN1993')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637150576','Toxic Solid, Organic, n.o.s. (Pomalidomide - Linker 2)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637150584','Toxic Solid, Organic, N.O.S. (Azido-Thalidomide)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637151326','Toxic Solid, Organis, N.O.S. (Thalidomide - Linker 3)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637151327','Toxic Solid, Organic, N.O.S. (Thalidomide - Linker 1)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637151328','Toxic Solid, Organic, N.O.S. (Thalidomide - Linker 2)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637152827','Toxic Solid, Organic, n.o.s. (Pomalidomide - Linker 3)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637152828','Toxic Solid, Organic, n.o.s. (Pomalidomide)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637152829','Toxic Solid, Organic, n.o.s. (Thalidomide, propargyl)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637153579','Toxic Solid, Organic, n.o.s. (L-DON)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637154326','Toxic Solid, Organic n.o.s. (dTAG-13)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637154332','Toxic Solid, Organic, n.o.s. (Thalidomide - linker 6)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637154333','Toxic Solid, Organic n.o.s. (Pomalidomide - linker 7)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637155076','Toxic Solid, Organic, N.O.S. (TL 13-12)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637156619','Toxic Solid, Organic, n.o.s. (Pomalidomide - Linker 4)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637156620','Toxic Solid, Organic, n.o.s. (Thalidomide - Linker 9)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637156621','Toxic Solid, Organic, n.o.s. (CRBN-6-5-5-VHL)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637156622','Toxic Solid, Organic, n.o.s. (Pomalidomide - Linker 8)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637157369','Toxic Solid, Organic, n.o.s. (Pomalidomide - Linker 1)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637157370','Toxic Solid, Organic, N.O.S (Thalidomide - linker 10)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637157371','Toxic Solid, Organic, N.O.S (Thalidomide - linker 12)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637157372','Toxic Solid, Organic, N.O.S (ZXH 3-26)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637158119','Toxic Solid, Organic, N.O.S (Thalidomide - linker 14)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637158120','Toxic Solid, Organic, N.O.S (Thalidomide - linker 15)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637158869','Toxic Solid, Organic, N.O.S (Thalidomide - linker 13)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637160412','Toxic Solid, Organic, n.o.s (Thalidomide - linker 4)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637161162','Toxic Solid, Organic, N.O.S (Thalidomide - linker 11)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637161163','Toxic Solid, Organic, N.O.S (CFT 2139)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637163498','Toxic Solid, Organic, N.O.S (aTAG 4531)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637164248','Toxic Solid, Organic, N.O.S. (Pomalidomide 4''-alkylC8-amine)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637165791','Toxic Solid, Organic, N.O.S. (NR 7h)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637166541','Toxic Solid, Organic, n.o.s. (dBET6)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637167291','Toxic Solid, Organic, N.O.S (FK-506)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637168041','Toxic Solid, Organic, N.O.S. (dBRD9-A)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637168042','Toxic Solid, Organic, N.O.S (Pomalidomide 4''-alkylC3-acid)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637168791','Toxic Solid, Organic, N.O.S (DD 03-171)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637169541','Toxic Solid, Organic, N.O.S (Pomalidomide 4''-alkylC7-acid)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637170291','Toxic Solid, Organic, N.O.S (Pomalidomide 4''-PEG1-acid)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637171041','Toxic solid, organic, n.o.s. (dTAG-13-NEG)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637171042','Toxic solid, organic, n.o.s. (Cisplatin)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637172541','Toxic Solid, Organic, N.O.S (Thalidomide 4''-oxyacetamide-alkylC1-PEG3-alkylC3-amine)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637172542','Toxic Solid, Organic, N.O.S (Thalidomide-Cyanine 5)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637173291','Toxic Solid, Organic, N.O.S (Pomalidomide 4''-PEG5-acid)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637173292','Toxic Solid, Organic, N.O.S (Thalidomide 4''-ether-alkylC7-acid)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637173293','Toxic Solid, Organic, N.O.S (Thalidomide 4''-ether-alkylC6-acid)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637173294','Toxic Solid, Organic, N.O.S (Thalidomide 4''-ether-alkylC5-acid)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637174041','Toxic Solid, Organic, N.O.S (Thalidomide 4''-ether-alkylC3-acid)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637174791','Toxic Solid, Organic, N.O.S (Thalidomide 4''-ether-alkylC4-acid)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637174792','Toxic Solid, Organic, N.O.S (Thalidomide 4''-ether-alkylC8-acid)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637175541','Toxic Solid, Organic, N.O.S (Thalidomide 4''-ether-alkylC2-acid)','6.1','UN2811')
Insert into #TempShipping (Code,[Name],IATA,UNNumber) values ('5637176291','Toxic Solid, Organic, N.O.S. (Deschloroclozapine)','6.1','UN2811')

Declare @SourceTable nvarchar(50)
Declare @SourceEntityID int
Declare @SourceModelID int
Declare @script nvarchar(1000)
SELECT @SourceModelID = ID from [mdm].[tblModel] where [Name] = 'AX' 
SELECT @SourceEntityID = ID from [mdm].[tblEntity] where Model_ID = @SourceModelID and [Name] = 'UNNumber'
SELECT @SourceTable = EntityTable from [mdm].[tblEntity] where ID = @SourceEntityID
Declare @SQL nvarchar(max)  = 'Insert into [stg].[ProperShippingName_Leaf] (BatchTag,ImportType, Code, Name, UNNumber, IATACLASSCODE) 
							  Select ''InsertShippingValues'',1,tp.Code,tp.[Name],unn.Code,tp.IATA from mdm.'+@SourceTable+' unn inner join #TempShipping tp on tp.UNNumber = unn.Name'  
EXEC sp_executesql @sql
exec [stg].[udp_ProperShippingName_Leaf] @VersionName=N'VERSION_1',@LogFlag=1, @BatchTag = 'InsertShippingValues'

--Shipping Name Extension

Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkylsulphonic acids, liquid solution','5637171791')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Ethanol solution','5637144576')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Methanol','5637144577')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Methyl acetate solution','5637144578')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloid salts, solid, n.o.s. ((-)-Lobeline hydrochloride)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloids, solid, n.o.s. (Camptothecin)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloids, solid, n.o.s. (Yohimbine hydrochloride)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloids, solid, n.o.s. (Colchicine)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloid, solid, n.o.s. ((-)-Cytisine)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloid, solid, n.o.s. (Homoharringtonine)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloid salts, solid, n.o.s. ((+)-Anabasine hydrochloride)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloid salts, solid, n.o.s. ((-)-Bicuculline methiodide)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloids, solid, n.o.s. (Caffeine)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloid salts, solid, n.o.s. ((+)-Tubocurarine chloride)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloids, solid, n.o.s. (Veratridine)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloids, solid, n.o.s. (Ellipticine)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloids, solid, n.o.s. (Vinorelbine ditartrate)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloid salts, solid, n.o.s. ((-)-Bicuculline methobromide)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloids, solid, n.o.s. ((+)-Bicuculline)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloid salts, solid, n.o.s. ((-)-Bicuculline methochloride)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloid salts, solid, n.o.s. (Cocaine hydrochloride)','5637144579')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Acetonitrile','5637144580')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'NIcotine preparation, solid, n.o.s. (RuBi-Nicotine)','5637144581')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Nicotine tartrate','5637144582')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Corrosive solid, n.o.s. (Zearalenone)','5637144584')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Corrosive liquid n.o.s. (Contains Trifluoroacetic acid)','5637144585')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Sodium Hydroxide Solution','5637144586')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alcohols, flammable, toxic, n.o.s. (Cell Activation Cocktail 500X in a 95% ethanol solution)','5637144587')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Flammable liquid, toxic, nos (Methanol,Acetone,Isopropanol)','5637144589')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Flammable liquid, toxic, n.o.s. (Methanol, Acetone, Isopropyl Alcohol)','5637144589')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Flammable liquid, toxic, nos (Methanol,Acetone,Isopropanol, N,N-Dimethylformamide, 3-Amino-9-Ethylca','5637144589')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Mercury compound,liquid,n.o.s.(4-Aminophenylmercury acetate)','5637144590')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Trichloroacetic Acid Solution','5637144591')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Sulphuric Acid','5637144592')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic Solid, Organic, N.O.S (aTAG 4531)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic liquid, organic, n.o.s. (Fentanyl citrate)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. ((+/-)-MDMA hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (D-Amphetamine sulfate)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Dexfenfluramine hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Diazepam)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Phencyclidine hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s.(Chlorphentermine hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Chlorisondamine diiodide)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Guanfacine hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Methysergide maleate)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Ouabain)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Iberiotoxin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Ketoconazole)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Quercetin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Resiniferatoxin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Oxymetazoline hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Calcitonin (salmon))','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (SR 57227 hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Actinomycin D)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Methotrexate)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Wortmannin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Anisomycin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (P1075)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Daunorubicin hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Milrinone)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (10Z-Hymenialdisine)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (NKH 477)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Lamotrigine)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Alprostadil)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Sulindac)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Indomethacin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Nilutamide)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Flurbiprofen)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Oxytocin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s.(pentostatin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. ((R)-(-)-Apomorphine hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Leflunomide)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Cisplatin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (SEW 2871)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Lamotrigine isethionate)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Tropisetron hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Nimesulide)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Calcitriol)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (GYKI 53655 hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Milameline hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Pentylenetetrazole)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Theophylline)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Carbamoylcholine chloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Mecamylamine hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Risperidone)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Tocriscreen Mini)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Ondansetron hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Alphaxalone)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. ((+)-Muscarine iodide)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Conantokin-T)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Conantokin-R)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Doxercalciferol)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (5-Fluorouracil)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Mitomycin C)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Milnacipran hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Valinomycin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Rotenone)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (FK-506)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Bendamustine hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Cevimeline hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Imiquimod)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Varenicline tartrate)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Voriconazole)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Etodolac)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Benidipine hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Ercalcitriol)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Deoxynivalenol)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Zotepine)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Lisuride maleate)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (6-Thioguanine)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Cyclophosphamide)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (6-Mercaptopurine)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Quinidine)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Niflumic acid)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Conantokin G)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Vitamin D3)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Tacalcitol)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Alfacalcidol)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. Beraprost sodium','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Diclofenac sodium salt)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Amitriptyline hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Paliperidone)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Flufenamic acid)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Phalloidin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. ((R)-(+)-Etomoxir sodium salt)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Auranofin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Penitrem A)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Melphalan)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Floxuridine)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s.(Decynium 22)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Apicidin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (3-Nitropropionic acid)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Cladribine)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Clozapine)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Donepezil hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Ibotenic acid)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Muscimol)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Ambenonium dichloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. ((RS)-Baclofen)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (CCCP)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (FCCP)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. ((E)-Capsaicin)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Malonoben)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Doxepin hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Methylergometrine maleate)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Physostigmine hemisulfate)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Thalidomide)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Verapamil hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. ((+/-)-Epibatidine)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Galanthamine hydrobromide)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Clonidine hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Pancuronium dibromide)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Riluzole hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. ((+/-)-Anatoxin A fumarate)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. ((R)-Baclofen)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Loperamide hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (EIT hydrobromide)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Guanabenz acetate)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Amiloride hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Ketanserin tartrate)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Haloperidol hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (4-Aminopyridine)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Piroxicam)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Buspirone hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Tacrine hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Cycloheximide)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Pindolol)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic solid, organic, n.o.s. (Cyproheptadine hydrochloride)','5637144593')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic liquid, organic, n.o.s. (Misoprostol)','5637144594')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Corrosive liquid, toxic, n.o.s. (Sulphuric Acid, Sodium Azide)','5637144596')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Environmentally hazardous substance, solid, n.o.s. (Dopamine hydrochloride)','5637144597')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Environmentally hazardous substance, solid, n.o.s. (Ropinirole hydrochloride)','5637144598')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Environmentally hazardous substance, solid, n.o.s. (Dapoxetine hydrochloride)','5637144598')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Environmentally hazardous substance,liquid,n.o.s.(Na Azide)','5637144598')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Environmentally hazardous substance, liquid, n.o.s.(Ethoxylatednonylphenol)','5637144598')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Environmentally hazardous substance, liquid, n.o.s.','5637144598')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Corrosive solid, basic, organic, n.o.s. (Tetradecyltrimethylammonium bromide)','5637144598')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Aviation regulated liquid, n.o.s(Formaldehyde betwn 10-25%)','5637144598')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins, extracted from living sources, solid, n.o.s. (Picrotoxin)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins, extracted from living sources, solid, n.o.s. (Okadaic acid)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins, extracted from living sources, solid, n.o.s. (Cytochalasin D)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins, extracted from living sources, solid, n.o.s. (Cyclopiazonic acid)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins, extracted from living sources, solid, n.o.s. (Ivermectin)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins, extracted from living sources, solid, n.o.s. (Ochratoxin A)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins, extracted from living sources, solid, n.o.s. (Calyculin)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins extracted from living sources, solid, n.o.s. (Gliotoxin)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins extracted from living sources, solid, n.o.s. (Concanamycin A)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins, extracted from living sources, solid, n.o.s. (Picropodophyllotoxin)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins extracted from living sources, solid, n.o.s. (Pertussis Toxin)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins, extracted from living sources, solid, n.o.s. (Celastrol)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic Solid, Organic, N.O.S (aTAG 4531)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic Solid, Organic, N.O.S (FK-506)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic Solid, Organic, N.O.S. (dBRD9-A)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic Solid, Organic, N.O.S (Pomalidomide 4''-alkylC3-acid)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins, extracted from living sources, solid, n.o.s. (Echinomycin)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins, extracted from living sources, solid, n.o.s. (Tetrodotoxin citrate)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins, extracted from living sources, solid, n.o.s. (Tetrodotoxin)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins, extracted from living sources, solid, n.o.s. (Tunicamycin)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins extracted from living sources, solid, n.o.s. (a-Amanitin)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins extracted from living sources, solid, n.o.s. (Hygromycin B)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins extracted from living sources, solid, n.o.s. (Nigericin sodium salt)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Environmentally hazardous substance, liquid, n.o.s. (Zinc Sulphate)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Flammable liquid, n.o.s. (Acetronitrile)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Alkaloids, solid, n.o.s. (Cytochalasin B)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Environmentally hazardous substance, solid,n.o.s. (AMG 853)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Flammable liquid, n.o.s. (Proprietary Buffer Mixture, Methanol, Proprietary Buffer Mixture)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic Solid, Organic, n.o.s. (Nephedrone hydrochloride)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic Solid, Organic, n.o.s. (Mephedrone hydrochloride)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxins extracted from living sources, solid, n.o.s.(Plumbagin)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic Solid, Organic, n.o.s. (Phentobarbital sodium)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Selenium compound, solid, N.O.S. (Ebselen)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic Solid, Organic, n.o.s. (Blasticidin S HCL)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Environmentally hazardous substance, solid, n.o.s.','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Environmentally hazardous substance, solid, n.o.s.(Ciliobrevin A)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic Solid, Organic, N.O.S. (L-DON)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic Solid, Organic, N.O.S (Thalidomide - linker 13)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic Solid, Organic, n.o.s. (Thalidomide - linker 4)','5637144603')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Hydrochloric acid','5637145326')
Insert into [stg].[ProperShippingNameExtension_Leaf] (BatchTag,ImportType, Name, [Proper Shipping Name])  values ('InsertExtension',1,'Toxic Solid, Organic, N.O.S (Pomalidomide 4''-alkylC3-acid)','5637168042')

exec [stg].[udp_ProperShippingNameExtension_Leaf] @VersionName=N'VERSION_1',@LogFlag=1, @BatchTag = 'InsertExtension'

END
